services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5435:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=artlist
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=artlist_user
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
