version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=artlist
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=artlist_user
      #    volumes:
      #      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  #volumes:
  ###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
